### ISSUE TITLE
Execute the Production Checklist

### ISSUE THREAD

**Issue by solaris007** [hlxsites/mammotome#175]
## Before Go-Live

- [x] [Content and Design QA](https://www.hlx.live/docs/go-live-checklist#content-and-design-qa)

Make sure that your content and design conforms to the specifications and that you are happy with the website you see on your projects .hlx.live domain. This may include checks for specific accessibility and SEO requirements of your project.

- [x] [Performance Validation](https://www.hlx.live/docs/go-live-checklist#performance-validation)

Every Franklin project should produce a lighthouse score of 100 for mobile and desktop from [Google Pagespeed insights](https://pagespeed.web.dev/) on its respective .hlx.live site.

See the document [Keeping it 100, Web Performance with Franklin](https://www.hlx.live/developer/keeping-it-100) for more information.

- [x] [Analytics Validation](https://www.hlx.live/docs/go-live-checklist#analytics-validation)

Make sure that all your analytics setup and the rest of your martech stack is firing as expected and visitor data is visible in your reporting dashboards.

- [x] [Legacy Redirects](https://www.hlx.live/docs/go-live-checklist#legacy-redirects)

In most migrations there are legacy URLs that are retired. Make sure those are reflected in your redirects spreadsheet (redirects.xlsx in sharepoint or redirects in google), found in your project content folder.

See the document [Redirects](https://www.hlx.live/docs/redirects) for more information.

- [x] [Sitemap & Robots](https://www.hlx.live/docs/go-live-checklist#sitemap--robots)

For most websites with a significant number of pages, a sitemap is desirable. Franklin automatically generates those from the query index.

If you have a sitemap that’s generated for your site make sure it is discoverable from your robots.txt. ​​

Note: hlx.page and hlx.live are kept hidden from crawlers intentionally, to avoid duplicate content.

See the documents [Indexing](https://www.hlx.live/developer/indexing) and [Sitemaps](https://www.hlx.live/developer/sitemap) for more information.

- [x] [Favicon](https://www.hlx.live/docs/go-live-checklist#favicon)

Adding a favicon to your site gives it a professional look in your visitor’s browsers.

See the document [Favicon](https://www.hlx.live/developer/favicon) for more information.

- [x] [CDN Configuration](https://www.hlx.live/docs/go-live-checklist#cdn-configuration)

One of the last steps in a go-live is usually to update your CDN configuration (e.g. Cloudflare, Fastly, Akamai, Cloudfront) to point to your hlx.live endpoint.

Ideally the CDN configuration is tested in a staging environment to make sure that everything works as expected.

Please see the following CDN setup documentation for more information.

[Cloudflare Worker Setup Guide](https://www.hlx.live/docs/byo-cdn-cloudflare-worker-setup)

- [x] [Push Invalidation Setup](https://www.hlx.live/docs/go-live-checklist#push-invalidation-setup)

Make sure push invalidation is properly set up according to the document [Configuring Push Invalidation for BYO Production CDN](https://www.hlx.live/docs/setup-byo-cdn-push-invalidation). Test the setup by publishing a small change and verifying that the change is visible on the production domain.

- [x] [Update Production Host](https://www.hlx.live/docs/go-live-checklist#update-production-host)

After setting up your production CDN, add the host property to the sidekick configuration in /tools/sidekick/config.json in your github repo, to allow your authors to navigate directly from the production domain to edit directly from the sidekick.

See the document [Sidekick Configuration](https://www.hlx.live/docs/sidekick#customizing-the-sidekick) for more information.

## Post Go-Live Validation

- [x] [Performance Validation](https://www.hlx.live/docs/go-live-checklist#performance-validation-1)

Validate that the performance is still at a lighthouse score of 100 via [pagespeed insights](https://pagespeed.web.dev/) on the production environment. Introducing a CDN layer can have adverse performance effects that are usually visible on the protocol layer. Typical culprits are running HTTP/1.1 or ineffective origin caching as well as bot detection or other libraries injected by the CDN configuration.

- [x] [Google Search Console](https://www.hlx.live/docs/go-live-checklist#google-search-console)

If you have an active Google Search Console with your sitemap uploaded, it may be valuable to get a coverage report and make sure that indexing works as expected. The Google Search Console should be monitored for the weeks after a go-live.

- [x] [404 Report](https://www.hlx.live/docs/go-live-checklist#report)

After a website has been migrated there is usually a set of 404 Not Founds, which should be monitored after the go-live and redirected to popular page URLs. This information can be pulled from your site analytics and the respective Franklin bot report. Monitoring this for the weeks after a go-live is recommended.
